# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.18

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho"

# Include any dependencies generated for this target.
include src\CMakeFiles\paho-mqtt3cs.dir\depend.make

# Include the progress variables for this target.
include src\CMakeFiles\paho-mqtt3cs.dir\progress.make

# Include the compile flags for this target's objects.
include src\CMakeFiles\paho-mqtt3cs.dir\flags.make

src\CMakeFiles\paho-mqtt3cs.dir\MQTTClient.c.obj: src\CMakeFiles\paho-mqtt3cs.dir\flags.make
src\CMakeFiles\paho-mqtt3cs.dir\MQTTClient.c.obj: ..\src\MQTTClient.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_1) "Building C object src/CMakeFiles/paho-mqtt3cs.dir/MQTTClient.c.obj"
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH\src
	C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\paho-mqtt3cs.dir\MQTTClient.c.obj /FdCMakeFiles\paho-mqtt3cs.dir\ /FS -c "C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\src\MQTTClient.c"
<<
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH

src\CMakeFiles\paho-mqtt3cs.dir\MQTTClient.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/paho-mqtt3cs.dir/MQTTClient.c.i"
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH\src
	C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\cl.exe > CMakeFiles\paho-mqtt3cs.dir\MQTTClient.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E "C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\src\MQTTClient.c"
<<
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH

src\CMakeFiles\paho-mqtt3cs.dir\MQTTClient.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/paho-mqtt3cs.dir/MQTTClient.c.s"
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH\src
	C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\paho-mqtt3cs.dir\MQTTClient.c.s /c "C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\src\MQTTClient.c"
<<
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH

src\CMakeFiles\paho-mqtt3cs.dir\SSLSocket.c.obj: src\CMakeFiles\paho-mqtt3cs.dir\flags.make
src\CMakeFiles\paho-mqtt3cs.dir\SSLSocket.c.obj: ..\src\SSLSocket.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_2) "Building C object src/CMakeFiles/paho-mqtt3cs.dir/SSLSocket.c.obj"
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH\src
	C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\paho-mqtt3cs.dir\SSLSocket.c.obj /FdCMakeFiles\paho-mqtt3cs.dir\ /FS -c "C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\src\SSLSocket.c"
<<
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH

src\CMakeFiles\paho-mqtt3cs.dir\SSLSocket.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/paho-mqtt3cs.dir/SSLSocket.c.i"
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH\src
	C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\cl.exe > CMakeFiles\paho-mqtt3cs.dir\SSLSocket.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E "C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\src\SSLSocket.c"
<<
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH

src\CMakeFiles\paho-mqtt3cs.dir\SSLSocket.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/paho-mqtt3cs.dir/SSLSocket.c.s"
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH\src
	C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\paho-mqtt3cs.dir\SSLSocket.c.s /c "C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\src\SSLSocket.c"
<<
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH

# Object files for target paho-mqtt3cs
paho__mqtt3cs_OBJECTS = \
"CMakeFiles\paho-mqtt3cs.dir\MQTTClient.c.obj" \
"CMakeFiles\paho-mqtt3cs.dir\SSLSocket.c.obj"

# External object files for target paho-mqtt3cs
paho__mqtt3cs_EXTERNAL_OBJECTS = \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\MQTTTime.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolClient.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\Clients.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\utf-8.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\MQTTPacket.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\MQTTPacketOut.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\Messages.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\Tree.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\Socket.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\Log.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\MQTTPersistence.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\Thread.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolOut.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\MQTTPersistenceDefault.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\SocketBuffer.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\LinkedList.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\MQTTProperties.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\MQTTReasonCodes.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\Base64.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\SHA1.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\WebSocket.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\StackTrace.c.obj" \
"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\common_ssl_obj.dir\Heap.c.obj"

src\paho-mqtt3cs.dll: src\CMakeFiles\paho-mqtt3cs.dir\MQTTClient.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\paho-mqtt3cs.dir\SSLSocket.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\MQTTTime.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolClient.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\Clients.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\utf-8.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\MQTTPacket.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\MQTTPacketOut.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\Messages.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\Tree.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\Socket.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\Log.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\MQTTPersistence.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\Thread.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolOut.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\MQTTPersistenceDefault.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\SocketBuffer.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\LinkedList.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\MQTTProperties.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\MQTTReasonCodes.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\Base64.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\SHA1.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\WebSocket.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\StackTrace.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\common_ssl_obj.dir\Heap.c.obj
src\paho-mqtt3cs.dll: src\CMakeFiles\paho-mqtt3cs.dir\build.make
src\paho-mqtt3cs.dll: C:\OpenSSL-Win64\lib\VC\libssl64MD.lib
src\paho-mqtt3cs.dll: C:\OpenSSL-Win64\lib\VC\libcrypto64MD.lib
src\paho-mqtt3cs.dll: src\CMakeFiles\paho-mqtt3cs.dir\objects1.rsp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir="C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_3) "Linking C shared library paho-mqtt3cs.dll"
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH\src
	"C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=CMakeFiles\paho-mqtt3cs.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests -- C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\link.exe  @CMakeFiles\paho-mqtt3cs.dir\objects1.rsp @<<
 /out:paho-mqtt3cs.dll /implib:paho-mqtt3cs.lib /pdb:"C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\paho-mqtt3cs.pdb" /dll /version:1.3 /machine:x64 /INCREMENTAL:NO  C:\OpenSSL-Win64\lib\VC\libssl64MD.lib C:\OpenSSL-Win64\lib\VC\libcrypto64MD.lib ws2_32.lib crypt32.lib RpcRT4.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  
<<
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH

# Rule to build all files generated by this target.
src\CMakeFiles\paho-mqtt3cs.dir\build: src\paho-mqtt3cs.dll

.PHONY : src\CMakeFiles\paho-mqtt3cs.dir\build

src\CMakeFiles\paho-mqtt3cs.dir\clean:
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH\src
	$(CMAKE_COMMAND) -P CMakeFiles\paho-mqtt3cs.dir\cmake_clean.cmake
	cd C:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH
.PHONY : src\CMakeFiles\paho-mqtt3cs.dir\clean

src\CMakeFiles\paho-mqtt3cs.dir\depend:
	$(CMAKE_COMMAND) -E cmake_depends "NMake Makefiles" "C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c" "C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\src" "C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho" "C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src" "C:\Users\Amuthamil Kavioviyan\Desktop\Philips\case study 2\paho\paho.mqtt.c\build.paho\src\CMakeFiles\paho-mqtt3cs.dir\DependInfo.cmake" --color=$(COLOR)
.PHONY : src\CMakeFiles\paho-mqtt3cs.dir\depend

