# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.18

# compile C with C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
C_DEFINES = -DPAHO_MQTT_EXPORTS=1 -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE

C_INCLUDES = 

C_FLAGS = /DWIN32 /D_WINDOWS /W3 /MD /O2 /Ob2 /DNDEBUG   -MD

