# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.18

# compile C with C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
C_DEFINES = -DOPENSSL=1 -DPAHO_MQTT_EXPORTS=1 -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE -Dpaho_mqtt3cs_EXPORTS

C_INCLUDES = -IC:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\src -IC:\Users\AMUTHA~1\Desktop\Philips\CASEST~2\paho\PAHOMQ~1.C\BUILD~1.PAH -IC:\OpenSSL-Win64\include

C_FLAGS = /DWIN32 /D_WINDOWS /W3 /MD /O2 /Ob2 /DNDEBUG   -MD

