name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: build 
      run: g++ -Wall -Wextra -Werror --coverage -o vendor *.cpp
    
    - name: run sender-test
      run: ./vendor
